### ISSUE TITLE
Missing `preProvisioningHook` in UpdateProvisioningTemplate API for CloudFormation

### ISSUE THREAD

**Issue by Gringox** [aws-cloudformation/aws-cloudformation-resource-providers-iot#10]
Hello there,

The API [UpdateProvisioningTemplate](https://docs.aws.amazon.com/iot/latest/apireference/API_UpdateProvisioningTemplate.html) has a parameter called `preProvisioningHook` which is missing from the update function in this repo:

https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-iot/blob/master/aws-iot-provisioningtemplate/src/main/java/com/amazonaws/iot/provisioningtemplate/UpdateHandler.java#L101

For reference, you can compare it to the create function which does have the `preProvisioningHook`:

https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-iot/blob/master/aws-iot-provisioningtemplate/src/main/java/com/amazonaws/iot/provisioningtemplate/CreateHandler.java#L107

Can you please add the `preProvisioningHook` to the update?

Thanks!

**Comment by molodand** [comment]
Fixed in https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-iot/commit/be69bfe93bbcf0248ed6f49232b5b895578e16a1
